





phonemes = {
    "de-DE": {},
    "en-US": { # https://learn.microsoft.com/de-de/azure/ai-services/speech-service/speech-ssml-phonetic-sets#section
        "iy": 1, 
        "ih": 2,
        "ey": 3,
        "eh": 4,
        "ae": 5,
        "aa": 6,
        "ao": 7,
        "uh": 8,
        "ow": 9,
        "uw": 10,
        "ah": 11,
        "ay": 12,
        "aw": 13,
        "oy": 14,
        "y": 15,
        "ax": 16,
        "er": 17,
        "w": 18,
        "j": 19,
        "p": 20,
        "b": 21,
        "t": 22,
        "T": 23,
        "k": 24,
        "g": 25,
        "m": 26,
        "n": 27,
        "ng": 28,
        "f": 29,
        "v": 30,
        "th": 31,
        "dh": 32,
        "s": 33,
        "z": 34,
        "sh": 35,
        "zh": 36,
        "h": 37,
        "ch": 38,
        "jh": 39,
        "l": 40,
        "r": 41,
    },
    "fr-FR": { # https://learn.microsoft.com/de-de/azure/ai-services/speech-service/speech-ssml-phonetic-sets#fr-frfr-cafr-ch
        "ae": 1,
        "af": 2,
        "ein": 3,
        "ax": 4,
        "eh": 5,
        "eu": 6,
        "ey": 7,
        "in": 8,
        "iy": 9,
        "oe": 10,
        "oh": 11,
        "on": 12,
        "ow": 13,
        "un": 14,
        "uw": 15,
        "uy": 16,
        "b": 17,
        "T": 18,
        "f": 19,
        "g": 20,
        "gn": 21,
        "hw": 22,
        "k": 23,
        "l": 24,
        "m": 25,
        "n": 26,
        "ng": 27,
        "p": 28,
        "r": 29,
        "s": 30,
        "sh": 31,
        "t": 32,
        "v": 33,
        "w": 34,
        "j": 35,
        "z": 36,
    },
    "en-GB": { # https://learn.microsoft.com/de-de/azure/ai-services/speech-service/speech-ssml-phonetic-sets#en-gben-ieen-au
    "ɑː": 1,
    "æ": 2,
    "ʌ": 3,
    "ɛə": 4,
    "aʊ": 5,
    "ə": 6,
    "aɪ": 7,
    "ɛ": 8,
    "ɜː": 9,
    "eɪ": 10,
    "ɪ": 11,
    "ɪə": 12,
    "iː": 13,
    "ɒ": 14,
    "ɔː": 15,
    "əʊ": 16,
    "ɔɪ": 17,
    "ʊ": 18,
    "ʊə": 19,
    "uː": 20,
    "b": 21,
    "tʃ": 22,
    "d": 23,
    "ð": 24,
    "f": 25,
    "g": 26,
    "h": 27,
    "j": 28,
    "dʒ": 29,
    "k": 30,
    "l": 31,
    "m": 32,
    "n": 33,
    "ŋ": 34,
    "p": 35,
    "ɹ": 36,
    "s": 37,
    "ʃ": 38,
    "t": 39,
    "θ": 40,
    "v": 41,
    "w": 42,
    "z": 43,
    "ʒ": 44,
    },
}




