# Generated by Django 4.1.10 on 2023-11-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('completeness', models.FloatField()),
                ('fluency', models.FloatField()),
                ('sentence', models.TextField()),
                ('recognized_sentence', models.TextField()),
                ('word_assessment', models.JSONField()),
                ('language', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
